### ISSUE TITLE
Onedrive Api search request always returns an empty collection

### ISSUE THREAD

**Issue by shahtajk7** [OneDrive/onedrive-api-docs#1394]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _Submission Guidelines:_
> - Questions and bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please provide clear reference(s) to the specific file(s) or URL('s).
> - Remember to include sufficient details and context.
> - If you have multiple issues, please submit them as separate issues so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

> For the above list, an empty checkbox is [ ]. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use the OneDrive Developer Platform UserVoice at http://aka.ms/od-dev-uservoice, or the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice.
> If you have a question about Azure Active Directory, outside of issues with the documentation provided in the OneDrive Developer Center, please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the observed behavior.
>
> Please also provide the following response headers corresponding to your request(s):
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug, please describe the steps to reproduce the bug in sufficient detail for another person to be able to reproduce it.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by shahtajk7** [comment]
I'm trying to search on OneDrive using this graph search api : https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http 
I have assigned all the required permissions (tried with application and delegated permissions both) , but I always receives an empty response with status code 200 from this api call :
    `https://graph.microsoft.com/v1.0/users/<user-id>/drive/root/search(q='some text')`

When I'm trying the same api call from graph explorer, it's returning all the search results. but when I try this on postman and my application, empty results are received. I'm really stuck here and any help will be really appreciated.
Thanks.

**Comment by shahtajk7** [comment]
This same question is posted here as well : https://github.com/OneDrive/onedrive-api-docs/issues/893 but there are no further replies (we are facing the same issue as last comment in above link).

**Comment by chackman** [comment]
Thanks for your feedback. We'll put this on our backlog to address.

**Comment by shahtajk7** [comment]
@chackman Can you kindly provide an ETA for the fix of this issue ? we actually need it urgently and we're facing this issue on our multiple paid accounts and we're blocked due to this.
Any help will be much appreciated, Thanks.

**Comment by chackman** [comment]
Could you please provide request ID's as requested above?

**Comment by shahtajk7** [comment]
Request Id : 22b42df4-0b78-4e29-9602-bae4acbd9c5f
Date : Fri, 23 Oct 2020 20:58:32 GMT

Response :
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": []
}
```

**Comment by shahtajk7** [comment]
Note: Moving forward few of my other team members will be responding on this thread.

**Comment by chackman** [comment]
We followed up with a partner team who have made a change which should address your tenant. Could you please confirm that it is working? If it is not working please provided new request ID + timestamp of the request that is not working?

**Comment by register110** [comment]
hi all, please help me. I have the same problem here, when I run it for the first time, an error occurs:
```{'error': {'code': 'generalException', 'message': 'An unspecified error has occurred.', 'innerError': {'date': '2020-10-30T00:36:00', 'request-id': '6d1f54a3-614c-43d1-b616-3f48f974e12a', 'client-request-id': '6d1f54a3-614c-43d1-b616-3f48f974e12a'}}}```

the second run succeeds, but an empty collection is returned::
```{'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)', 'value': []}```

>We followed up with a partner team who have made a change which should address your tenant

So, is this a bug that cannot be fixed yet and can only be fixed for specific people?

**Comment by mauze-muawwaz** [comment]
@chackman We'll get back to you with the answers.

**Comment by mauze-muawwaz** [comment]
I can confirm that it is working for the tenant in question (referred to by our developer [here](https://github.com/OneDrive/onedrive-api-docs/issues/1394#issuecomment-715587469)

`Request Id : 22b42df4-0b78-4e29-9602-bae4acbd9c5f
Date : Fri, 23 Oct 2020 20:58:32 GMT`

@chackman We still have other faulty tenants. Which brings me to the next question, is it not a global fix? Why is it a tenant level fix?

It still doesn't work for this tenant of ours

> https://graph.microsoft.com/v1.0/users/9e02c20b-f706-48bc-9664-4d8d9d67c9b8/drive/root/search(q='Admin@gmail.com​')

`cache-control →private
client-request-id →d2872367-5fd1-457e-95cf-890b038ad0b9
content-encoding →gzip
content-length →206
content-type →application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
date →Tue, 03 Nov 2020 14:58:57 GMT
odata-version →4.0
request-id →d2872367-5fd1-457e-95cf-890b038ad0b9
strict-transport-security →max-age=31536000
vary →Accept-Encoding
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"Southeast Asia","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_16"}}`

**Comment by mauze-muawwaz** [comment]
@register110 what did you do to make it work?

**Comment by register110** [comment]
@mauze-muawwaz I did nothing, the only way to solve this problem is to wait for Microsoft developers to fix it：）

**Comment by shahtajk7** [comment]
As mentioned by my other team member above, it started working for the tenants we mentioned above. But the question is, is the fix tenant specific and not global ? To verify, I created a new tenant after search started working on above mentioned tenants and search didn't work on that newly created tenant (empty search results were returned).

**Comment by mauze-muawwaz** [comment]
I don't know what sort of monitoring is in place. This is still an outstanding issue. Fixing tenants one by one using request ID is not a scalable solution for the many(all new ones) tenants that run into this problem.

**Comment by chackman** [comment]
Apologies, but we are still following up with the search team regarding this issue.

**Comment by shahtajk7** [comment]
@chackman Sure, thanks. We're looking forward to hear back on this.

**Comment by mauze-muawwaz** [comment]
@chackman Thanks for the update.

**Comment by anund-lie** [comment]
Sending app context privileged query request via the MSGraph or Vroom APIs can be expected to work, but there’s no general guarantee that all functionality exposed by the Sharepoint Search API is available or will work exactly the same when querying Sharepoint entities via MSGraph.
As far as we could tell, the tenants mentioned in this GitHub issue were affected by a known problem that is now fixed (but may have become effective for different tenants at different points in time).

**Comment by mauze-muawwaz** [comment]
@anund-lie could you please let us know what the problem was? and how to identify that? We could then try to validate before issuing these searches and then scratch our heads as to why it's not working.

**Comment by anund-lie** [comment]
This was an internal issue in the search backend.  There is nothing that could be done on user side to detect or address the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by k-tsoi** [comment]
@mauze-muawwaz  @shahtajk7 is this issue resolved? if so please close out this issue.

**Comment by cguZZman** [comment]
It is not resolved.
I have the same issue with the following request:
```
Cache-Control: private
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
request-id: 04db856d-9b3e-4f61-b4aa-62bd79eb2c64
client-request-id: 04db856d-9b3e-4f61-b4aa-62bd79eb2c64
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"004","RoleInstance":"AGSFE_IN_39"}}
OData-Version: 4.0
Strict-Transport-Security: max-age=31536000
Date: Thu, 04 Feb 2021 19:27:57 GMT
Connection: close
Content-Length: 96
```

This was the response:
Response (200) content-length=96, len=<96>:
```
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)","value":[]}
```

Can somebody take a look?

**Comment by k-tsoi** [comment]
@anund-lie could you update on this

**Comment by chackman** [comment]
@anund-lie could you update on this

**Comment by davyarris** [comment]
It was making me dizzy reading this and so I thought I might make this link for those that are still possibly facing this problem.

Please refer to this post in another bug that states that read access to ROOT is required in order for the search to operate as expected. This is not by design and is still a bug I believe?

See [this post](https://github.com/OneDrive/onedrive-api-docs/issues/893#issuecomment-465930124) for further information.

I believe that post triggered this ticket which has been investigating for nearly 2 years!

[Search requires caller to have access to "context site" #1010](https://github.com/OneDrive/onedrive-api-docs/issues/1010)

**Comment by k-tsoi** [comment]
@anund-lie could you provide an update for this issue

**Comment by anund-lie** [comment]
I'm sorry, I can't.  No results from search (if that's the reason here) is a very generic symptom that may have multiple underlying reasons.  I was called in to investigate a issue in a specific component a couple of levels down in the stack.  To rule out issues related to the search kernel itself, such as incorrect search customizations or permission settings, my suggestion is to investigate using the classic SharePoint query API directly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AmritSinghGit** [comment]
Wow can't believe Microsoft won't fix it. I am facing the same issue

**Comment by cguZZman** [comment]
This is the issue link: https://github.com/OneDrive/onedrive-api-docs/issues/1394

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
