### ISSUE TITLE
Use a refresh_token to gain a new access token

### ISSUE THREAD

**Issue by opicko** [OneDrive/onedrive-api-docs#372]
I am trying to understand how to get a new access token from a cached refresh_token for OneDrive for Business. The documentation does not describe what API calls need to made to accomplish this. The following instructions explain the process but not how to do this with the API.

I am having a problem mapping your 4 steps to APIcalls? It very confusing having an API but all the documentaion refers to URIs?

can you reword the following four steps to the specific API calls required?

1: Initial OAuth authorization through login.windows.net/oauth2/authorize?client_id={clientId}&scope=MyFiles.Write&response_type=code&redirect_uri={appUrl}
This returns back to you an authorization code.

2: Redeem the authorization code for an access_token and refresh_token for the Office Discovery Service
POST to login.windows.net/common/oauth2/token with the following form parameters:
client_id, client_secret, redirect_uri, code, grant_type, and resource=https://api.office.com/discovery/

Note: You need to have the value of resource be exactly “https://api.office.com/discovery/” with the trailing /, otherwise the access token you get back won’t be valid.

3: Store the refresh_token securely for later. Even though you specify the resource for the discovery service in the request, the refresh_token value you receive is good for any service you’ve been authorized to access by the user. That means this refresh_token will get you into the OneDrive for Business, you just need to redeem it with the proper resource value later.

4: Use the access_token from #2 to make a request to the discovery service to find the OneDrive for Business URL:
GET https://api.office.com/discovery/v1.0/me/services
Authorization: Bearer {access_token}

**Comment by rgregg** [comment]
The API call is an HTTP request you need to make, which is described here: https://dev.onedrive.com/auth/aad_oauth.htm#step-4-redeem-refresh-token-for-an-access-token-to-call-onedrive-api

If you are using one of the OneDrive SDKs then this step should be taken care of for you. Are you using an SDK or using the REST API directly?

**Comment by opicko** [comment]
Yes, I am trying to use the OneDriveSdk.dll oneDrivesdk.windowsForms.dll

                    this.oneDriveClient = BusinessClientExtensions.GetActiveDirectoryClient(FormBrowser.AadClientId, FormBrowser.AadReturnUrl);
                }
            }

            try
            {
                if (!this.oneDriveClient.IsAuthenticated)
                {
                    await this.oneDriveClient.AuthenticateAsync();

This piece of code is doing the authentication when I select the “sign in to aad” option in the sample code and it works
But I cannot figure out how to save the refresh token and then use it to request a new  access token.

**Comment by opicko** [comment]
I have been trying to follow the instructions in your link but this does not seem to be working for me

https://login.microsoftonline.com/common/oauth2/Token?client_id=e1801d98-8aef-4d5d-b4cc-0634c828d31a&redirect_uri=https://license.omtool.com/redirect/&grant_type=refresh_token&refresh_token=AAABAAAAiL9Kn2Z27UubvWFPbm0gLczBe6UACW7fX1WypUgtWRetX7XHp9JrAq5XUFHDICbqZ2FJhMznHaOwmcq-aU6w8kGGoGLg-wGa0b2e4n5wWR3JXAx6jV6gVeFhsc-KA6N2zwBzbLXR5oz3J-GpaVK1W8ruIxcCOx2OHqwMgmiQD853ilkOKQfKezPFm8_YQnja6XOykZDEm_PsWh5xvTEtfk-_ppl9aJSwdNrCHlsuhJNuyW1hqc_-mK1Lod8HgO_Jo9BDYk2Zv6256ONvIkHvhEtqcaZVWmIMmDKME0gkKdWHGgV8yA0qqB88LvgIxIUOywDzF-_kka38gTdUdwbZOAgWCn2euDEgOjPWlYIArnXsB3Kr19iYAoJCkazfaNzzjghRFkMY5PPPiUc0aD63jdy9cpPDYUVO57bOWFUQhQ9vBr43h0VaUpwA2cnYjRKni5_AFzhGYJnwxCSxp4pH_czLMqqnZG7qaYy0kzHlR-IVQW8b6GRu2D8PE66hcY-Sw2YQGGUdMPxym3BB_tFxqebiyqYI2ZWhf699BvhqVG3XUMFLz98Tkp0D1k02oRTnbSlEkA11CV2RQfXgkfNvOOR5DFSN4kImxs1kdzx3U9sQNfqC8XwWgNUQCgpAEJiBFtGDMItZttYk0LQGb9HlhNNMFZs8PE9u6bLWij4PoEsgAA&resource=https://omtool.sharepoint.com/

**Comment by ginach** [comment]
@opicko, we've just pushed a new version of the OneDriveSDK package that supports initializing a OneDrive for Business client using a refresh token. You can do this using BusinessClientExtensions.GetSilentlyAuthenticatedClientAsync().

As for retrieving refresh token from a previous authentication request, this should be set in client.AuthenticationProvider.CurrentAccountSession.RefreshToken, if it was returned by the first authenticate call.

**Comment by opicko** [comment]
Gina,

Can you provide a fragment of how this call is made? The following snippet

Complains “IOneDriveCLient” does not contain a definition for “GetAwaiter”

           await this.oneDriveClient = BusinessClientExtensions.GetSilentlyAuthenticatedClientAsync(
                            new BusinessAppConfig
                            {
                                ActiveDirectoryAppId = AadClientId,
                                ActiveDirectoryReturnUrl = AadReturnUrl,
                            }, m_sRefreshToken);

Bill

**Comment by ginach** [comment]
@opicko, you'll want to await the async method and not the client:

 this.oneDriveClient = await BusinessClientExtensions.GetSilentlyAuthenticatedClientAsync(
                            new BusinessAppConfig
                            {
                                ActiveDirectoryAppId = AadClientId,
                                ActiveDirectoryReturnUrl = AadReturnUrl,
                            }, m_sRefreshToken);

**Comment by opicko** [comment]
Gina,

I have modified FormBrowser.cs and added a RefreshSignIn() method and added my hard coded values required to do a refresh from token signin. I still get an “authentication failure”.

How long does the refresh_token last?

Bill

**Comment by opicko** [comment]
this.oneDriveClient = await BusinessClientExtensions.GetSilentlyAuthenticatedClientAsync()

when I make the above call I get the following exception?

AADSTS50001: The application named https://omtool-my.sharepoint.com/_api/v2.0/me was not found in the tenant named 0fc1435a-1295-4804-882b-c99004d550b5.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: 28f04c41-b023-4ccb-896f-b9583caaac62
Correlation ID: 90c32405-8009-4462-b35f-5c0b0f1fbd02
Timestamp: 2016-06-01 17:51:43Z

Where does the tenant come from I don't provide it in the call?

**Comment by ginach** [comment]
After following up offline, this was due to using an incorrect service resource ID. Closing issue.

**Comment by ohs0612** [comment]
Hello Gina, 

Is that possible to get OneDriveClient object with "refresh token"or "access token" instead of using the authentication process on Android device by java code?
Because user has already login my web server, so I can have these two tokens from backend server. And I would like to retrieve the user data from OneDrive.

I know it is not directly related to the topic here, just really want to know by the way.

Thank you a lot in advance.

Odee
